# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'admin_panel.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(681, 675)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: #111133")
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 0, 661, 631))
        self.tabWidget.setStyleSheet("background-color: #111111")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(280, 20, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setStyleSheet("color: white")
        self.label.setObjectName("label")
        self.pushButton_adminpanel_add = QtWidgets.QPushButton(self.tab)
        self.pushButton_adminpanel_add.setGeometry(QtCore.QRect(40, 250, 571, 111))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_adminpanel_add.setFont(font)
        self.pushButton_adminpanel_add.setStyleSheet("QPushButton {\n"
"    color: #ff6666;\n"
"    background-color: #222222;\n"
"    border-color: rgb(66, 69, 183);\n"
"     border-width: 3px;        \n"
"     border-style: solid;\n"
"     border-radius: 50px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: #333333;\n"
"    color: 220000;\n"
"}")
        self.pushButton_adminpanel_add.setObjectName("pushButton_adminpanel_add")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(280, 120, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: white")
        self.label_2.setObjectName("label_2")
        self.lineEdit_adminpanel_pasword = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_adminpanel_pasword.setGeometry(QtCore.QRect(40, 160, 569, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lineEdit_adminpanel_pasword.setFont(font)
        self.lineEdit_adminpanel_pasword.setStyleSheet("background-color: #999999;\n"
"color: white;\n"
"border-radius: 20;\n"
"border-color: red")
        self.lineEdit_adminpanel_pasword.setObjectName("lineEdit_adminpanel_pasword")
        self.label_adminpanel_check = QtWidgets.QLabel(self.tab)
        self.label_adminpanel_check.setGeometry(QtCore.QRect(90, 430, 461, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_adminpanel_check.setFont(font)
        self.label_adminpanel_check.setStyleSheet("color: white")
        self.label_adminpanel_check.setText("")
        self.label_adminpanel_check.setObjectName("label_adminpanel_check")
        self.lineEdit_adminpanel_login = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_adminpanel_login.setGeometry(QtCore.QRect(40, 60, 569, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lineEdit_adminpanel_login.setFont(font)
        self.lineEdit_adminpanel_login.setStyleSheet("background-color: #999999;\n"
"color: white;\n"
"border-radius: 20;\n"
"border-color: red")
        self.lineEdit_adminpanel_login.setObjectName("lineEdit_adminpanel_login")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.lineEdit_adminpanel_add_price = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_adminpanel_add_price.setGeometry(QtCore.QRect(190, 230, 381, 51))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lineEdit_adminpanel_add_price.setFont(font)
        self.lineEdit_adminpanel_add_price.setStyleSheet("color: white;\n"
"background-color: #555555;\n"
"border-radius: 10")
        self.lineEdit_adminpanel_add_price.setObjectName("lineEdit_adminpanel_add_price")
        self.lineEdit_adminpanel_add_name = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_adminpanel_add_name.setGeometry(QtCore.QRect(190, 40, 381, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lineEdit_adminpanel_add_name.setFont(font)
        self.lineEdit_adminpanel_add_name.setStyleSheet("color: white;\n"
"background-color: #555555;\n"
"border-radius: 10")
        self.lineEdit_adminpanel_add_name.setObjectName("lineEdit_adminpanel_add_name")
        self.textEdit_adminpanel_add_description = QtWidgets.QTextEdit(self.tab_2)
        self.textEdit_adminpanel_add_description.setGeometry(QtCore.QRect(190, 140, 381, 51))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.textEdit_adminpanel_add_description.setFont(font)
        self.textEdit_adminpanel_add_description.setStyleSheet("color: white;\n"
"background-color: #555555;\n"
"border-radius: 8")
        self.textEdit_adminpanel_add_description.setObjectName("textEdit_adminpanel_add_description")
        self.layoutWidget = QtWidgets.QWidget(self.tab_2)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 20, 161, 381))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_14 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("color: white")
        self.label_14.setObjectName("label_14")
        self.verticalLayout_3.addWidget(self.label_14)
        self.label_15 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("color: white")
        self.label_15.setObjectName("label_15")
        self.verticalLayout_3.addWidget(self.label_15)
        self.label_16 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("color: white")
        self.label_16.setObjectName("label_16")
        self.verticalLayout_3.addWidget(self.label_16)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: white")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.pushButton_adminpanel_add_object = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_adminpanel_add_object.setGeometry(QtCore.QRect(20, 420, 551, 121))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.pushButton_adminpanel_add_object.setFont(font)
        self.pushButton_adminpanel_add_object.setStyleSheet("QPushButton {\n"
"    color: #ff6666;\n"
"    background-color: #222222;\n"
"    border-color: rgb(66, 69, 183);\n"
"     border-width: 3px;        \n"
"     border-style: solid;\n"
"     border-radius: 50px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: #333333;\n"
"    color: 220000;\n"
"}")
        self.pushButton_adminpanel_add_object.setObjectName("pushButton_adminpanel_add_object")
        self.comboBox_adminpanel_add_kategory = QtWidgets.QComboBox(self.tab_2)
        self.comboBox_adminpanel_add_kategory.setGeometry(QtCore.QRect(190, 330, 381, 41))
        self.comboBox_adminpanel_add_kategory.setStyleSheet("color: white;\n"
"background-color: #555555;")
        self.comboBox_adminpanel_add_kategory.setObjectName("comboBox_adminpanel_add_kategory")
        self.label_add_objects_itog = QtWidgets.QLabel(self.tab_2)
        self.label_add_objects_itog.setGeometry(QtCore.QRect(10, 560, 631, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_add_objects_itog.setFont(font)
        self.label_add_objects_itog.setStyleSheet("color: white")
        self.label_add_objects_itog.setText("")
        self.label_add_objects_itog.setObjectName("label_add_objects_itog")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.pushButton_sale = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_sale.setGeometry(QtCore.QRect(30, 280, 591, 101))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_sale.setFont(font)
        self.pushButton_sale.setStyleSheet("QPushButton {\n"
"    color: #ff6666;\n"
"    background-color: #222222;\n"
"    border-color: rgb(66, 69, 183);\n"
"     border-width: 3px;        \n"
"     border-style: solid;\n"
"     border-radius: 50px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: #333333;\n"
"    color: 220000;\n"
"}")
        self.pushButton_sale.setObjectName("pushButton_sale")
        self.layoutWidget1 = QtWidgets.QWidget(self.tab_3)
        self.layoutWidget1.setGeometry(QtCore.QRect(30, 50, 591, 161))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: white;")
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.comboBox_sale_number = QtWidgets.QComboBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.comboBox_sale_number.setFont(font)
        self.comboBox_sale_number.setStyleSheet("color: white;\n"
"background-color: #555555;")
        self.comboBox_sale_number.setObjectName("comboBox_sale_number")
        self.verticalLayout.addWidget(self.comboBox_sale_number)
        self.label_add_sale_itog = QtWidgets.QLabel(self.tab_3)
        self.label_add_sale_itog.setGeometry(QtCore.QRect(40, 440, 561, 51))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_add_sale_itog.setFont(font)
        self.label_add_sale_itog.setStyleSheet("color: white")
        self.label_add_sale_itog.setText("")
        self.label_add_sale_itog.setObjectName("label_add_sale_itog")
        self.tabWidget.addTab(self.tab_3, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 681, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Login:"))
        self.pushButton_adminpanel_add.setText(_translate("MainWindow", "Добавить"))
        self.label_2.setText(_translate("MainWindow", "Password:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Добавить администратора"))
        self.label_14.setText(_translate("MainWindow", "Название:"))
        self.label_15.setText(_translate("MainWindow", "Описание:"))
        self.label_16.setText(_translate("MainWindow", "Цена:"))
        self.label_3.setText(_translate("MainWindow", "Категория:"))
        self.pushButton_adminpanel_add_object.setText(_translate("MainWindow", "Добавить"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Добавить предмет"))
        self.pushButton_sale.setText(_translate("MainWindow", "Добавить"))
        self.label_4.setText(_translate("MainWindow", "Количество товаров со скидкой"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Создать скидки"))
