# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Dialog_Register.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(616, 391)
        Dialog.setStyleSheet("background-color: #111122")
        self.pushButton_register = QtWidgets.QPushButton(Dialog)
        self.pushButton_register.setGeometry(QtCore.QRect(310, 210, 280, 91))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_register.setFont(font)
        self.pushButton_register.setStyleSheet("QPushButton{\n"
"    background-color: #444444;\n"
"    color: white;\n"
"    border-radius: 40;\n"
"    border-color: red\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: #666666;\n"
"    color: #111111;\n"
"}")
        self.pushButton_register.setObjectName("pushButton_register")
        self.pushButton_enter = QtWidgets.QPushButton(Dialog)
        self.pushButton_enter.setGeometry(QtCore.QRect(20, 210, 281, 91))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_enter.setFont(font)
        self.pushButton_enter.setStyleSheet("QPushButton{\n"
"    background-color: #444444;\n"
"    color: white;\n"
"    border-radius: 40;\n"
"    border-color: red\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: #666666;\n"
"    color: #111111;\n"
"}")
        self.pushButton_enter.setObjectName("pushButton_enter")
        self.lineEdit_pasword = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_pasword.setGeometry(QtCore.QRect(30, 140, 569, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lineEdit_pasword.setFont(font)
        self.lineEdit_pasword.setStyleSheet("background-color: #999999;\n"
"color: white;\n"
"border-radius: 20;\n"
"border-color: red")
        self.lineEdit_pasword.setObjectName("lineEdit_pasword")
        self.lineEdit_login = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_login.setGeometry(QtCore.QRect(30, 50, 569, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lineEdit_login.setFont(font)
        self.lineEdit_login.setStyleSheet("background-color: #999999;\n"
"color: white;\n"
"border-radius: 20;\n"
"border-color: red")
        self.lineEdit_login.setObjectName("lineEdit_login")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(260, 10, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setStyleSheet("color: white")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(250, 100, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: white")
        self.label_2.setObjectName("label_2")
        self.label_check = QtWidgets.QLabel(Dialog)
        self.label_check.setGeometry(QtCore.QRect(110, 320, 391, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_check.setFont(font)
        self.label_check.setStyleSheet("color: white")
        self.label_check.setText("")
        self.label_check.setObjectName("label_check")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton_register.setText(_translate("Dialog", "Зарегистрироваться"))
        self.pushButton_enter.setText(_translate("Dialog", "Войти"))
        self.label.setText(_translate("Dialog", "Login:"))
        self.label_2.setText(_translate("Dialog", "Password:"))
