# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Dialog_mode.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(430, 108)
        Dialog.setStyleSheet("background-color: #AAAAAA")
        self.pushButton_entrance = QtWidgets.QPushButton(Dialog)
        self.pushButton_entrance.setGeometry(QtCore.QRect(10, 30, 201, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_entrance.setFont(font)
        self.pushButton_entrance.setStyleSheet("QPushButton{\n"
"    background-color: #666666;\n"
"    color: white;\n"
"    border-radius: 20;\n"
"    border-color: red\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: #888888;\n"
"    color: #111111;\n"
"}")
        self.pushButton_entrance.setObjectName("pushButton_entrance")
        self.pushButton_admin = QtWidgets.QPushButton(Dialog)
        self.pushButton_admin.setGeometry(QtCore.QRect(220, 30, 201, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_admin.setFont(font)
        self.pushButton_admin.setStyleSheet("QPushButton{\n"
"    background-color: #666666;\n"
"    color: white;\n"
"    border-radius: 20;\n"
"    border-color: red\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: #888888;\n"
"    color: #111111;\n"
"}")
        self.pushButton_admin.setObjectName("pushButton_admin")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton_entrance.setText(_translate("Dialog", "Вход"))
        self.pushButton_admin.setText(_translate("Dialog", "Администрирование"))
