# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'proect_shop.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1120, 904)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: #002244")
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 0, 1101, 851))
        self.tabWidget.setStyleSheet("background-color: #111111")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(10, 10, 71, 41))
        font = QtGui.QFont()
        font.setFamily("Space Bd BT")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setStyleSheet("color: white")
        self.label.setObjectName("label")
        self.label_glavnaya_top1 = QtWidgets.QLabel(self.tab)
        self.label_glavnaya_top1.setGeometry(QtCore.QRect(50, 70, 550, 550))
        self.label_glavnaya_top1.setText("")
        self.label_glavnaya_top1.setObjectName("label_glavnaya_top1")
        self.label_glavnaya_top2 = QtWidgets.QLabel(self.tab)
        self.label_glavnaya_top2.setGeometry(QtCore.QRect(680, 10, 391, 291))
        self.label_glavnaya_top2.setText("")
        self.label_glavnaya_top2.setObjectName("label_glavnaya_top2")
        self.label_glavnaya_top3 = QtWidgets.QLabel(self.tab)
        self.label_glavnaya_top3.setGeometry(QtCore.QRect(689, 419, 401, 291))
        self.label_glavnaya_top3.setText("")
        self.label_glavnaya_top3.setObjectName("label_glavnaya_top3")
        self.textEdit_glavnaya_top2 = QtWidgets.QTextEdit(self.tab)
        self.textEdit_glavnaya_top2.setGeometry(QtCore.QRect(720, 310, 231, 101))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.textEdit_glavnaya_top2.setFont(font)
        self.textEdit_glavnaya_top2.setStyleSheet("background-color: #444444;\n"
"color: white;\n"
"border-radius: 40;\n"
"border-color: red")
        self.textEdit_glavnaya_top2.setObjectName("textEdit_glavnaya_top2")
        self.textEdit_glavnaya_top1 = QtWidgets.QTextEdit(self.tab)
        self.textEdit_glavnaya_top1.setGeometry(QtCore.QRect(10, 650, 471, 161))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.textEdit_glavnaya_top1.setFont(font)
        self.textEdit_glavnaya_top1.setStyleSheet("background-color: #444444;\n"
"color: white;\n"
"border-radius: 40;\n"
"border-color: red")
        self.textEdit_glavnaya_top1.setObjectName("textEdit_glavnaya_top1")
        self.pushButton_glavnaya_top2 = QtWidgets.QPushButton(self.tab)
        self.pushButton_glavnaya_top2.setGeometry(QtCore.QRect(960, 310, 121, 101))
        font = QtGui.QFont()
        font.setPointSize(35)
        self.pushButton_glavnaya_top2.setFont(font)
        self.pushButton_glavnaya_top2.setStyleSheet("QPushButton {\n"
"    color: #ff6666;\n"
"    background-color: #222222;\n"
"    border-color: rgb(66, 69, 183);\n"
"     border-width: 3px;        \n"
"     border-style: solid;\n"
"     border-radius: 50px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: #333333;\n"
"    color: 220000;\n"
"}")
        self.pushButton_glavnaya_top2.setObjectName("pushButton_glavnaya_top2")
        self.pushButton_glavnaya_top1 = QtWidgets.QPushButton(self.tab)
        self.pushButton_glavnaya_top1.setGeometry(QtCore.QRect(500, 650, 171, 161))
        font = QtGui.QFont()
        font.setPointSize(45)
        self.pushButton_glavnaya_top1.setFont(font)
        self.pushButton_glavnaya_top1.setStyleSheet("QPushButton {\n"
"    color: #ff6666;\n"
"    background-color: #222222;\n"
"    border-color: rgb(66, 69, 183);\n"
"     border-width: 3px;        \n"
"     border-style: solid;\n"
"     border-radius: 50px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: #333333;\n"
"    color: 220000;\n"
"}")
        self.pushButton_glavnaya_top1.setObjectName("pushButton_glavnaya_top1")
        self.textEdit_glavnaya_top3 = QtWidgets.QTextEdit(self.tab)
        self.textEdit_glavnaya_top3.setGeometry(QtCore.QRect(720, 710, 231, 101))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.textEdit_glavnaya_top3.setFont(font)
        self.textEdit_glavnaya_top3.setStyleSheet("background-color: #444444;\n"
"color: white;\n"
"border-radius: 40;\n"
"border-color: red")
        self.textEdit_glavnaya_top3.setObjectName("textEdit_glavnaya_top3")
        self.pushButton_glavnaya_top3 = QtWidgets.QPushButton(self.tab)
        self.pushButton_glavnaya_top3.setGeometry(QtCore.QRect(960, 710, 121, 101))
        font = QtGui.QFont()
        font.setPointSize(35)
        self.pushButton_glavnaya_top3.setFont(font)
        self.pushButton_glavnaya_top3.setStyleSheet("QPushButton {\n"
"    color: #ff6666;\n"
"    background-color: #222222;\n"
"    border-color: rgb(66, 69, 183);\n"
"     border-width: 3px;        \n"
"     border-style: solid;\n"
"     border-radius: 50px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: #333333;\n"
"    color: 220000;\n"
"}")
        self.pushButton_glavnaya_top3.setObjectName("pushButton_glavnaya_top3")
        self.tabWidget.addTab(self.tab, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.comboBox_electro_search = QtWidgets.QComboBox(self.tab_5)
        self.comboBox_electro_search.setGeometry(QtCore.QRect(10, 50, 321, 51))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.comboBox_electro_search.setFont(font)
        self.comboBox_electro_search.setStyleSheet("background-color: #77777e;\n"
"color: white")
        self.comboBox_electro_search.setObjectName("comboBox_electro_search")
        self.textEdit_electro_description = QtWidgets.QTextEdit(self.tab_5)
        self.textEdit_electro_description.setGeometry(QtCore.QRect(210, 290, 361, 81))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.textEdit_electro_description.setFont(font)
        self.textEdit_electro_description.setStyleSheet("color: white;\n"
"background-color: #555555;\n"
"border-radius: 8")
        self.textEdit_electro_description.setObjectName("textEdit_electro_description")
        self.lineEdit_electro_id = QtWidgets.QLineEdit(self.tab_5)
        self.lineEdit_electro_id.setGeometry(QtCore.QRect(210, 120, 361, 51))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lineEdit_electro_id.setFont(font)
        self.lineEdit_electro_id.setStyleSheet("color: white;\n"
"background-color: #555555;\n"
"border-radius: 10")
        self.lineEdit_electro_id.setObjectName("lineEdit_electro_id")
        self.lineEdit_electro_price = QtWidgets.QLineEdit(self.tab_5)
        self.lineEdit_electro_price.setGeometry(QtCore.QRect(210, 400, 361, 61))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lineEdit_electro_price.setFont(font)
        self.lineEdit_electro_price.setStyleSheet("color: white;\n"
"background-color: #555555;\n"
"border-radius: 10")
        self.lineEdit_electro_price.setObjectName("lineEdit_electro_price")
        self.lineEdit_electro_name = QtWidgets.QLineEdit(self.tab_5)
        self.lineEdit_electro_name.setGeometry(QtCore.QRect(210, 210, 361, 51))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lineEdit_electro_name.setFont(font)
        self.lineEdit_electro_name.setStyleSheet("color: white;\n"
"background-color: #555555;\n"
"border-radius: 10")
        self.lineEdit_electro_name.setObjectName("lineEdit_electro_name")
        self.pushButton_electro_search = QtWidgets.QPushButton(self.tab_5)
        self.pushButton_electro_search.setGeometry(QtCore.QRect(310, -20, 291, 161))
        font = QtGui.QFont()
        font.setFamily("Swiss921 BT")
        font.setPointSize(16)
        self.pushButton_electro_search.setFont(font)
        self.pushButton_electro_search.setStyleSheet("QPushButton {\n"
"    color: #ff6666;\n"
"    background-color: #222222;\n"
"    border-color: rgb(66, 69, 183);\n"
"     border-width: 3px;        \n"
"     border-style: solid;\n"
"     border-radius: 10px;\n"
"     margin:30px;\n"
"     padding:30px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: #333333;\n"
"    color: 220000;\n"
"}")
        self.pushButton_electro_search.setObjectName("pushButton_electro_search")
        self.layoutWidget = QtWidgets.QWidget(self.tab_5)
        self.layoutWidget.setGeometry(QtCore.QRect(40, 110, 161, 361))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_9 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color: white")
        self.label_9.setObjectName("label_9")
        self.verticalLayout_2.addWidget(self.label_9)
        self.label_10 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color: white")
        self.label_10.setObjectName("label_10")
        self.verticalLayout_2.addWidget(self.label_10)
        self.label_13 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("color: white")
        self.label_13.setObjectName("label_13")
        self.verticalLayout_2.addWidget(self.label_13)
        self.label_12 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("color: white")
        self.label_12.setObjectName("label_12")
        self.verticalLayout_2.addWidget(self.label_12)
        self.pushButton_electro_like = QtWidgets.QPushButton(self.tab_5)
        self.pushButton_electro_like.setGeometry(QtCore.QRect(80, 520, 361, 231))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.pushButton_electro_like.setFont(font)
        self.pushButton_electro_like.setStyleSheet("QPushButton {\n"
"    color: #ff6666;\n"
"    background-color: #222222;\n"
"    border-color: rgb(66, 69, 183);\n"
"     border-width: 3px;        \n"
"     border-style: solid;\n"
"     border-radius: 10px;\n"
"     margin:30px;\n"
"     padding:30px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: #333333;\n"
"    color: 220000;\n"
"}")
        self.pushButton_electro_like.setObjectName("pushButton_electro_like")
        self.label_electro_photo = QtWidgets.QLabel(self.tab_5)
        self.label_electro_photo.setGeometry(QtCore.QRect(590, 20, 500, 780))
        self.label_electro_photo.setText("")
        self.label_electro_photo.setObjectName("label_electro_photo")
        self.label_14 = QtWidgets.QLabel(self.tab_5)
        self.label_14.setGeometry(QtCore.QRect(20, 10, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("color: white")
        self.label_14.setObjectName("label_14")
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.lineEdit_cofe_id = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_cofe_id.setGeometry(QtCore.QRect(210, 130, 361, 51))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lineEdit_cofe_id.setFont(font)
        self.lineEdit_cofe_id.setStyleSheet("color: white;\n"
"background-color: #555555;\n"
"border-radius: 10")
        self.lineEdit_cofe_id.setObjectName("lineEdit_cofe_id")
        self.pushButton_cofe_like = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_cofe_like.setGeometry(QtCore.QRect(80, 530, 361, 231))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.pushButton_cofe_like.setFont(font)
        self.pushButton_cofe_like.setStyleSheet("QPushButton {\n"
"    color: #ff6666;\n"
"    background-color: #222222;\n"
"    border-color: rgb(66, 69, 183);\n"
"     border-width: 3px;        \n"
"     border-style: solid;\n"
"     border-radius: 10px;\n"
"     margin:30px;\n"
"     padding:30px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: #333333;\n"
"    color: 220000;\n"
"}")
        self.pushButton_cofe_like.setObjectName("pushButton_cofe_like")
        self.layoutWidget_2 = QtWidgets.QWidget(self.tab_4)
        self.layoutWidget_2.setGeometry(QtCore.QRect(40, 120, 161, 361))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_11 = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color: white")
        self.label_11.setObjectName("label_11")
        self.verticalLayout_3.addWidget(self.label_11)
        self.label_15 = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("color: white")
        self.label_15.setObjectName("label_15")
        self.verticalLayout_3.addWidget(self.label_15)
        self.label_16 = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("color: white")
        self.label_16.setObjectName("label_16")
        self.verticalLayout_3.addWidget(self.label_16)
        self.label_17 = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("color: white")
        self.label_17.setObjectName("label_17")
        self.verticalLayout_3.addWidget(self.label_17)
        self.pushButton_cofe_search = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_cofe_search.setGeometry(QtCore.QRect(310, -10, 291, 161))
        font = QtGui.QFont()
        font.setFamily("Swiss921 BT")
        font.setPointSize(16)
        self.pushButton_cofe_search.setFont(font)
        self.pushButton_cofe_search.setStyleSheet("QPushButton {\n"
"    color: #ff6666;\n"
"    background-color: #222222;\n"
"    border-color: rgb(66, 69, 183);\n"
"     border-width: 3px;        \n"
"     border-style: solid;\n"
"     border-radius: 10px;\n"
"     margin:30px;\n"
"     padding:30px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: #333333;\n"
"    color: 220000;\n"
"}")
        self.pushButton_cofe_search.setObjectName("pushButton_cofe_search")
        self.textEdit_cofe_description = QtWidgets.QTextEdit(self.tab_4)
        self.textEdit_cofe_description.setGeometry(QtCore.QRect(210, 300, 361, 81))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.textEdit_cofe_description.setFont(font)
        self.textEdit_cofe_description.setStyleSheet("color: white;\n"
"background-color: #555555;\n"
"border-radius: 8")
        self.textEdit_cofe_description.setObjectName("textEdit_cofe_description")
        self.lineEdit_cofe_price = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_cofe_price.setGeometry(QtCore.QRect(210, 410, 361, 61))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lineEdit_cofe_price.setFont(font)
        self.lineEdit_cofe_price.setStyleSheet("color: white;\n"
"background-color: #555555;\n"
"border-radius: 10")
        self.lineEdit_cofe_price.setObjectName("lineEdit_cofe_price")
        self.label_18 = QtWidgets.QLabel(self.tab_4)
        self.label_18.setGeometry(QtCore.QRect(20, 20, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("color: white")
        self.label_18.setObjectName("label_18")
        self.lineEdit_cofe_name = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_cofe_name.setGeometry(QtCore.QRect(210, 220, 361, 51))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lineEdit_cofe_name.setFont(font)
        self.lineEdit_cofe_name.setStyleSheet("color: white;\n"
"background-color: #555555;\n"
"border-radius: 10")
        self.lineEdit_cofe_name.setObjectName("lineEdit_cofe_name")
        self.comboBox_cofe_search = QtWidgets.QComboBox(self.tab_4)
        self.comboBox_cofe_search.setGeometry(QtCore.QRect(10, 60, 321, 51))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.comboBox_cofe_search.setFont(font)
        self.comboBox_cofe_search.setStyleSheet("background-color: #77777e;\n"
"color: white")
        self.comboBox_cofe_search.setObjectName("comboBox_cofe_search")
        self.label_cofe_photo = QtWidgets.QLabel(self.tab_4)
        self.label_cofe_photo.setGeometry(QtCore.QRect(590, 30, 500, 780))
        self.label_cofe_photo.setText("")
        self.label_cofe_photo.setObjectName("label_cofe_photo")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.pushButton_sport_like = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_sport_like.setGeometry(QtCore.QRect(80, 530, 361, 231))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.pushButton_sport_like.setFont(font)
        self.pushButton_sport_like.setStyleSheet("QPushButton {\n"
"    color: #ff6666;\n"
"    background-color: #222222;\n"
"    border-color: rgb(66, 69, 183);\n"
"     border-width: 3px;        \n"
"     border-style: solid;\n"
"     border-radius: 10px;\n"
"     margin:30px;\n"
"     padding:30px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: #333333;\n"
"    color: 220000;\n"
"}")
        self.pushButton_sport_like.setObjectName("pushButton_sport_like")
        self.lineEdit_sport_id = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_sport_id.setGeometry(QtCore.QRect(210, 130, 361, 51))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lineEdit_sport_id.setFont(font)
        self.lineEdit_sport_id.setStyleSheet("color: white;\n"
"background-color: #555555;\n"
"border-radius: 10")
        self.lineEdit_sport_id.setObjectName("lineEdit_sport_id")
        self.textEdit_sport_description = QtWidgets.QTextEdit(self.tab_2)
        self.textEdit_sport_description.setGeometry(QtCore.QRect(210, 300, 361, 81))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.textEdit_sport_description.setFont(font)
        self.textEdit_sport_description.setStyleSheet("color: white;\n"
"background-color: #555555;\n"
"border-radius: 8")
        self.textEdit_sport_description.setObjectName("textEdit_sport_description")
        self.comboBox_sport_search = QtWidgets.QComboBox(self.tab_2)
        self.comboBox_sport_search.setGeometry(QtCore.QRect(10, 60, 321, 51))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.comboBox_sport_search.setFont(font)
        self.comboBox_sport_search.setStyleSheet("background-color: #77777e;\n"
"color: white")
        self.comboBox_sport_search.setObjectName("comboBox_sport_search")
        self.pushButton_sport_search = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_sport_search.setGeometry(QtCore.QRect(310, -10, 291, 161))
        font = QtGui.QFont()
        font.setFamily("Swiss921 BT")
        font.setPointSize(16)
        self.pushButton_sport_search.setFont(font)
        self.pushButton_sport_search.setStyleSheet("QPushButton {\n"
"    color: #ff6666;\n"
"    background-color: #222222;\n"
"    border-color: rgb(66, 69, 183);\n"
"     border-width: 3px;        \n"
"     border-style: solid;\n"
"     border-radius: 10px;\n"
"     margin:30px;\n"
"     padding:30px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: #333333;\n"
"    color: 220000;\n"
"}")
        self.pushButton_sport_search.setObjectName("pushButton_sport_search")
        self.label_19 = QtWidgets.QLabel(self.tab_2)
        self.label_19.setGeometry(QtCore.QRect(20, 20, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("color: white")
        self.label_19.setObjectName("label_19")
        self.layoutWidget_3 = QtWidgets.QWidget(self.tab_2)
        self.layoutWidget_3.setGeometry(QtCore.QRect(40, 120, 161, 361))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget_3)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_20 = QtWidgets.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet("color: white")
        self.label_20.setObjectName("label_20")
        self.verticalLayout_4.addWidget(self.label_20)
        self.label_21 = QtWidgets.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_21.setFont(font)
        self.label_21.setStyleSheet("color: white")
        self.label_21.setObjectName("label_21")
        self.verticalLayout_4.addWidget(self.label_21)
        self.label_22 = QtWidgets.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_22.setFont(font)
        self.label_22.setStyleSheet("color: white")
        self.label_22.setObjectName("label_22")
        self.verticalLayout_4.addWidget(self.label_22)
        self.label_23 = QtWidgets.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_23.setFont(font)
        self.label_23.setStyleSheet("color: white")
        self.label_23.setObjectName("label_23")
        self.verticalLayout_4.addWidget(self.label_23)
        self.label_sport_photo = QtWidgets.QLabel(self.tab_2)
        self.label_sport_photo.setGeometry(QtCore.QRect(590, 30, 500, 780))
        self.label_sport_photo.setText("")
        self.label_sport_photo.setObjectName("label_sport_photo")
        self.lineEdit_sport_price = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_sport_price.setGeometry(QtCore.QRect(210, 410, 361, 61))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lineEdit_sport_price.setFont(font)
        self.lineEdit_sport_price.setStyleSheet("color: white;\n"
"background-color: #555555;\n"
"border-radius: 10")
        self.lineEdit_sport_price.setObjectName("lineEdit_sport_price")
        self.lineEdit_sport_name = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_sport_name.setGeometry(QtCore.QRect(210, 220, 361, 51))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lineEdit_sport_name.setFont(font)
        self.lineEdit_sport_name.setStyleSheet("color: white;\n"
"background-color: #555555;\n"
"border-radius: 10")
        self.lineEdit_sport_name.setObjectName("lineEdit_sport_name")
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1120, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Top:"))
        self.pushButton_glavnaya_top2.setText(_translate("MainWindow", "<3"))
        self.pushButton_glavnaya_top1.setText(_translate("MainWindow", "<3"))
        self.pushButton_glavnaya_top3.setText(_translate("MainWindow", "<3"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Главнаяя"))
        self.pushButton_electro_search.setText(_translate("MainWindow", "Найти"))
        self.label_9.setText(_translate("MainWindow", "ID:"))
        self.label_10.setText(_translate("MainWindow", "Название:"))
        self.label_13.setText(_translate("MainWindow", "Описание:"))
        self.label_12.setText(_translate("MainWindow", "Цена:"))
        self.pushButton_electro_like.setText(_translate("MainWindow", "<3"))
        self.label_14.setText(_translate("MainWindow", "Название товара:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "Электротехника"))
        self.pushButton_cofe_like.setText(_translate("MainWindow", "<3"))
        self.label_11.setText(_translate("MainWindow", "ID:"))
        self.label_15.setText(_translate("MainWindow", "Название:"))
        self.label_16.setText(_translate("MainWindow", "Описание:"))
        self.label_17.setText(_translate("MainWindow", "Цена:"))
        self.pushButton_cofe_search.setText(_translate("MainWindow", "Найти"))
        self.label_18.setText(_translate("MainWindow", "Название товара:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Кофе"))
        self.pushButton_sport_like.setText(_translate("MainWindow", "<3"))
        self.pushButton_sport_search.setText(_translate("MainWindow", "Найти"))
        self.label_19.setText(_translate("MainWindow", "Название товара:"))
        self.label_20.setText(_translate("MainWindow", "ID:"))
        self.label_21.setText(_translate("MainWindow", "Название:"))
        self.label_22.setText(_translate("MainWindow", "Описание:"))
        self.label_23.setText(_translate("MainWindow", "Цена:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Спорт"))
